# Generated by Django 3.2.7 on 2022-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_auto_20220711_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='port',
            field=models.IntegerField(choices=[(0, 'Port 0'), (1, 'Port 1')], default=0),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='slot',
            field=models.IntegerField(choices=[(0, 'Slot 0'), (1, 'Slot 1')], default=0),
        ),
        migrations.AddConstraint(
            model_name='interfaces',
            constraint=models.UniqueConstraint(fields=('device', 'ip4_address'), name='unique address'),
        ),
    ]
