# Generated by Django 3.2.7 on 2022-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0003_auto_20220712_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='slot',
            field=models.IntegerField(choices=[(0, 'Slot 0'), (1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3'), (4, 'Slot 4'), (5, 'Slot 5'), (6, 'Slot 6'), (7, 'Slot 7'), (8, 'Slot 8'), (9, 'Slot 9')], default=0),
        ),
    ]
